eyetracker.hw.gazepoint.gp3.EyeTracker:
    name: tracker
    enable: IOHUB_BOOL
    model_name:
        IOHUB_LIST:
            valid_values: [GP3, GP3 HD]
            min_length: 1
            max_length: 1
    serial_number:
        IOHUB_STRING:
            min_length: 0
            max_length: 32
    save_events: IOHUB_BOOL
    stream_events: IOHUB_BOOL
    auto_report_events: False
    network_settings:
        ip_address: IOHUB_IP_ADDRESS_V4
        port:
            IOHUB_INT:
                min: 1
                max: 9999
    event_buffer_length: 
        IOHUB_INT:
            min: 1
            max: 8192
    device_timer:
        interval:
            IOHUB_FLOAT:
                min: 0.001
                max: 0.020
    monitor_event_types:           
        IOHUB_LIST:
            valid_values: [GazepointSampleEvent, BinocularEyeSampleEvent, FixationStartEvent, FixationEndEvent]
            min_length: 1
            max_length: 3
    runtime_settings:
        sampling_rate: Auto
        track_eyes: [BINOCULAR,]
    calibration:
        target_delay:
            IOHUB_FLOAT:
                min: 0.25
                max: 2.5
        target_duration:
            IOHUB_FLOAT:
                min: 0.25
                max: 2.5
        use_builtin: IOHUB_BOOL
        # Remaining calibration config settings only apply if use_builtin == False
        auto_pace: True # GazePoint only supports auto_pace = True, do not change
        type:
            IOHUB_LIST:
                valid_values: [THREE_POINTS,FIVE_POINTS,NINE_POINTS, THIRTEEN_POINTS]
                min_length: 1
                max_length: 1
        unit_type:
            IOHUB_LIST:
                valid_values: [norm, pix, cm, height, deg, degFlatPos, degFlat]
                min_length: 0
                max_length: 1
        color_type:
            IOHUB_LIST:
                valid_values: [rgb, dkl, lms, hsv, hex, named, rgb255]
                min_length: 0
                max_length: 1
        randomize: IOHUB_BOOL
        screen_background_color: IOHUB_COLOR
        text_color: IOHUB_COLOR
        target_type:
            IOHUB_LIST:
                valid_values: [CIRCLE_TARGET, CUSTOM]
                min_length: 1
                max_length: 1
        target_attributes:
            custom:
                module_name:
                class_name:
                class_kwargs:
            outer_diameter:
                IOHUB_FLOAT:
                    min: 0.01
                    max: 1000.0
            outer_stroke_width:
                IOHUB_FLOAT:
                    min: 0.01
                    max: 1000.0
            outer_fill_color: IOHUB_COLOR
            outer_line_color: IOHUB_COLOR
            inner_diameter:
                IOHUB_FLOAT:
                    min: 0.01
                    max: 1000.0
            inner_stroke_width:
                IOHUB_FLOAT:
                    min: 0.01
                    max: 1000.0
            inner_fill_color: IOHUB_COLOR
            inner_line_color: IOHUB_COLOR
            animate:
                enable: IOHUB_BOOL
                expansion_ratio:
                    IOHUB_FLOAT:
                        min: 1.0
                        max: 100.0
                contract_only: IOHUB_BOOL
    device_number: 0
    manufacturer_name: GazePoint
