eyetracker.hw.pupil_labs.pupil_core.EyeTracker:

    name: 
        IOHUB_STRING:
            min_length: 1
            max_length: 32
            first_char_alpha: True

    device_number: 0

    #####

    model_name:
        IOHUB_LIST:
            valid_values: [Pupil Core]
            min_length: 0
            max_length: 1

    serial_number:
        IOHUB_STRING:
            min_length: 0
            max_length: 32

    model_number:
        IOHUB_STRING:
            min_length: 1
            max_length: 16

    software_version:
        IOHUB_STRING:
            min_length: 1
            max_length: 8

    hardware_version:
        IOHUB_STRING:
            min_length: 1
            max_length: 8

    firmware_version: 
        IOHUB_STRING:
            min_length: 1
            max_length: 8

    #####

    enable: IOHUB_BOOL

    manufacturer_name: Pupil Labs

    monitor_event_types:
        IOHUB_LIST:
            valid_values: [MonocularEyeSampleEvent, BinocularEyeSampleEvent]
            min_length: 1
            max_length: 2

    save_events: IOHUB_BOOL

    stream_events: IOHUB_BOOL

    auto_report_events: False

    event_buffer_length: 
        IOHUB_INT:
            min: 1
            max: 2048
